apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: hello-minikube
  name: hello-minikube
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: hello-minikube
  type: NodePort
status:
  loadBalancer: {}
